server {
    listen 80;
    server_name localhost;

    # Директория со скомпилированной статикой
    root /usr/share/nginx/html;
    index index.html;

    # Обработка SPA: если файл не найден — возвращаем index.html (маршрут отработает во Vue)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статических файлов
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Отключение логов для фавикона
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    # Ошибки сервера (50x)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
